# Site settings
# in the templates available like {{ site.myvariable }}.
title: Statistical Coffee&Tea Tasting.
email: eight.cups.and.a.lady@gmail.com
brand: 8 cups and a Lady
headline: ご婦人と８つのカップ
description: > # this means to ignore newlines until "baseurl:"
  Statistical Coffee&Tea Tasting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2019 Eight cups and a Lady, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 664345

# Contacts
email: eight.cups.and.a.lady@gmail.com
phone: #+1-800-555-2016

# Tracking
#googleAnalitycsID: UA-83933844-1

